### ISSUE TITLE
Why no Java?

### ISSUE THREAD

**Issue by hising** [lsjostro/dotfiles#2]
My app needs Java for bytecode. Why you no Java in dotfiles? I do need it, can we install on machine, yes?

Kind regards,
Kuklachyov Anatoliy (Tolya) Gennadiyevich

**Comment by hising** [comment]
I cucumber, you cat. HAHA!

![](https://media.giphy.com/media/8zdi3lQp3fzKU/source.gif)

**Comment by lsjostro** [comment]
Sorry, i make Java no more. You fork some one else, ok? Good luck 🙉

**Comment by hising** [comment]
> 
> 
> Sorry, i make Java no more. You fork some one else, ok? Good luck 🙉

Yes.

**Comment by hising** [comment]
We now will make other software use for our company. :disappointed: 

Kind regards,
Kuklachyov Anatoliy (Tolya) Gennadiyevich

**Comment by hising** [comment]
I has download now, what is your home address  so I can visit you and say "thanks"

Kind regards,
Kuklachyov Anatoliy (Tolya) Gennadiyevich
